### ISSUE TITLE
Map within Maps?

### ISSUE THREAD

**Issue by bradennapier** [pascalduez/postcss-map#118]
I find myself copying a lot of code in my maps to make various fully-fledged styles that I use all over the place.  For example, I define my colors and want to be able to use them but also to define @map properties to apply to an element.  Would be nice to make it highly configurable without needing to change values in every little place when a simply color change is attempted.  This also allows adding more "relative" type configurations, obviously allowing to @map inside might create circular requires so probably just allowing map().

**Comment by pascalduez** [comment]
Hi,

this is a bit cryptic to me as is, would you mind providing a few examples?

**Comment by agogel** [comment]
Hi @pascalduez,

if I'm getting it right, @bradennapier asks for something like this:

*Case 1 - Getting a value of another map*

map 1:
```
# global.yml
color:
  primary: #f00
```
  
map 2:
```
# foo.yml
color: map(global, color, primary)
```

input:
```
.foo {
  color: map(foo, color);
}
```

output:
```
.foo {
  color: #f00;
}
```

---

*Case 2: Getting a value of the same map*
  
map:
```
# foo.yml
color: #f00
border-color: map(foo, color)
```

input:
```
.foo {
  color: map(foo, color);
  border-color: map(foo, border-color);
}
```

output:
```
.foo {
  color: #f00;
  border-color: #f00;
}
```

---

If Braden meant that, I'm with him. Especially case 1 could be very useful. :-)  

Case 2 would be nice to have, too. In case of the current approach I am considerding at least as long as [globbing is not possible](https://github.com/pascalduez/postcss-map/issues/28) - as work-around for globbing I'm merging all `*.config.yml` files into one `config.yml` first.

Anyway, thanks for this handy plugin!

**Comment by RedHatter** [comment]
Case 1 should be documented. I came here looking for it.

**Comment by RedHatter** [comment]
@agogel I can't get case one working. I tried your exact example. I'll include a simplified inline version here for completeness.

    const postcss = require('postcss');
    const map = require('postcss-map');
    postcss()
      .use(map({
        maps: [{
          global: {
            primary: 'red'
          },
          foo: {
            color: 'map(global, primary)'
          }
        }
      ]}))
      .process(`
        .foo {
          color: map(global, primary);
          color: map(foo, color);
        }
      `)
      .then(result => {
        console.log(result.css)
      });
