### ISSUE TITLE
Consider adding path-style map arguments

### ISSUE THREAD

**Issue by thedeeno** [pascalduez/postcss-map#12]
Instead of this: `map(font, size, large)`
It'd be nice to write: `map('font.size.large')`

When scanning my css I keep thinking the tokens in the first style API are variables, not path segments. I think making it a string would make the path aspect clearer.

**Comment by TrySound** [comment]
Not seems as expectable css construction.

**Comment by pascalduez** [comment]
Agree, while I understand the motivation I would like to stay as close as possible to what could potentially be a native CSS implementation.
