### ISSUE TITLE
yaml filename

### ISSUE THREAD

**Issue by TrySound** [pascalduez/postcss-map#20]
Need to add filename to yaml options for more informative error message

**Comment by pascalduez** [comment]
Could you please elaborate a bit ? With examples.

**Comment by TrySound** [comment]
before
```
    YAMLException: end of the stream or a document separator is expected at line 4, column 3:
          item
          ^
```
after
```
    YAMLException: end of the stream or a document separator is expected in "D:\Workflow\github\postcss-map\test\fixture
\fail.yml" at line 4, column 3:
          item
          ^
```

We can have many yaml files and don't understand where is the problem.

**Comment by pascalduez** [comment]
Definitely better. 
I would still make a pass on user friendly error reporting.
