### ISSUE TITLE
Map from declaration blocks with variables

### ISSUE THREAD

**Issue by catherinelamonde** [pascalduez/postcss-map#57]
Is it possible to do something like «@map fonts primary normal $font-weight;» ?

«@map fonts primary normal $font-weight;» gives me the error : Cannot convert undefined or null to object.

Thank you,
Catherine

**Comment by pascalduez** [comment]
Hi,

I suppose you're using the `postcss-simple-vars` plugin, it should be run __before__ the `postcss-map` one.
If `$font-weight` translate to an existing map key before `postcss-map` parse it, it should be fine.
